### ISSUE TITLE
Question - How to transfer val3 from USB to the controller?

### ISSUE THREAD

**Issue by Niknu** [ros-industrial/staubli_val3_driver#28]
Hi there,

I'm not sure how I should transfer the val3 driver to the controller, you are writing as followed:

" There are multiple ways of transferring VAL 3 applications to the controller:
1. Copy the contents of val3 folder onto a USB memory stick (<2GB if using CS8), plugging the stick into the controller and using the teach pendant to copy the folders "

In my case, I have a CS8 controller and the controller can see the USB stick with ros_libs + ros_server.
But when I try to load the ros_server it says something with the incorrect type in SimpleRosMsg on the line 1.

I'm doing it correctly, or?

**Comment by pratipo** [comment]
hi
exactly the same here, git cloned the repo in ubuntu 18.04, then copied the contents of /val3

controller: cs8c
val: 7.11.2

**Comment by gavanderhoorn** [comment]
This starts to sound a bit like #27. Could you both take a look?

**Comment by Niknu** [comment]
I have tried to clone and download zip on Linux and Windows. It doesn't work with the #27 solution, 

What I have is :

Controller : cs8
System: s.7.9.1

Below is images of what I assume is needed information

![IMG_20210219_110819](https://user-images.githubusercontent.com/37380867/108490828-78fcc800-72a3-11eb-897d-1473c082d312.jpg)
![IMG_20210219_111027](https://user-images.githubusercontent.com/37380867/108490836-7a2df500-72a3-11eb-9386-5ecf75950388.jpg)
![IMG_20210219_111537](https://user-images.githubusercontent.com/37380867/108491558-5c14c480-72a4-11eb-8fcc-adb56cd37ae3.jpg)

### **_When I see the Event loggers output_**

![IMG_20210219_111553](https://user-images.githubusercontent.com/37380867/108491553-5a4b0100-72a4-11eb-94de-2e2e527cb52a.jpg)
![IMG_20210219_111615](https://user-images.githubusercontent.com/37380867/108491557-5b7c2e00-72a4-11eb-826c-26929a8c0c9d.jpg)
![IMG_20210219_111619](https://user-images.githubusercontent.com/37380867/108491559-5c14c480-72a4-11eb-8512-4ac3e3756ccc.jpg)

**Comment by gavanderhoorn** [comment]
So both with the `.zip` as with `git clone` gives you these errors?

**Comment by gavanderhoorn** [comment]
As this seems to be the same -- or a similar enough -- error as in #27, I'd like to suggest we re-open #27 and continue there.

**Comment by gavanderhoorn** [comment]
I'm going to close this one, we'll continue in #27.
