### ISSUE TITLE
Strange accel override

### ISSUE THREAD

**Issue by simonschmeisser** [ros-industrial/staubli_val3_driver#3]
https://github.com/ros-industrial/staubli_val3_driver/blob/55b4fe6d3fbc60fa7a89139aa0f195c5d3c62072/staubli_val3_driver/val3/ros_server/pushMotion.pgx#L77

sets the acceleration (deceleration) to 9999 if velocity override is activated. This is motivated by a  reference to the manual and Val3's default value. However in said manual the acceleration is specified to be in percent, ie in the range of 100 to 0. 9999 is the default value for tcp velocity.

Our customer set this to 60 and obtained good results, 9999 was apparently very un-smooth and not visually pleasing

**Comment by gavanderhoorn** [comment]
I've linked #8, as it changes the implementation of the override.

As I wrote in #1 though, I believe we should remove it entirely.
