### ISSUE TITLE
ros_server NOT running in CS9 controller

### ISSUE THREAD

**Issue by AshwathamanGovind** [ros-industrial/staubli_val3_driver#33]
When i tried to start the ros_server after sending the contents inside the val3 directory to the usrapp/ directory in cs9. An error saying "cannot start ros_server.pgx" is shown and i am not able to start the server. I am using a cs9 controller and TX2_60 Robot here and i am making use of the staubli driver that i got from https://github.com/ros-industrial/staubli_val3_driver/ . Can you anyone help me sort out this problem and establish a seamless communication between ROS and staubli cs9 ??? 

Thanks in Advance. Any help from your side would be of great use for me

**Comment by gavanderhoorn** [comment]
As far as we know, CS9 should be supported and work. This was contributed by @marshallpowell97 in #15.

Are there are any more informative (error) messages displayed then `cannot start ros_server.pgx`?

Perhaps you could take a picture of the TP when it shows you that error?

**Comment by AshwathamanGovind** [comment]
This is error that i get when i try to run the ros_server from SP2 in Staubli 
![Staubli_error](https://user-images.githubusercontent.com/78215878/121480110-5a544580-c9e8-11eb-9238-79e5d749d262.jpeg)

**Comment by JohannesFriedrich** [comment]
Just a little hint from my side: 
You also have to load the "ros_libs" folder to usrapp. It looks like in your image that this library is not on the disk.

**Comment by AshwathamanGovind** [comment]
@JohannesFriedrich 
I have loaded that ros_libs folder also to usrapp. I also checked that again using ftp. The folder is present inside usrapp but it is not listed in the VAL3 APPLICATIONS tab in the teach pendant. I have attached the snapshot of the file structure (accessed using FTP).
![staubli_ros_libs_pic](https://user-images.githubusercontent.com/78215878/121520140-33116e80-ca10-11eb-939d-dd1c84369277.png)

**Comment by JohannesFriedrich** [comment]
What´s the error logger (upper left symbol) exactly saying? Can you give us a screenshot or better: an exported error-logger? You can export it also via ftp by changing the directory to _log_ or export it via USB by exporting it in the error-logger panel, click right on the little arrow (sub-menu) and export it.

**Comment by AshwathamanGovind** [comment]
Please have a look. I have attached the exported error log folder that i have exported from CS9. 
[exportLogs.zip](https://github.com/ros-industrial/staubli_val3_driver/files/6631692/exportLogs.zip)

**Comment by AshwathamanGovind** [comment]
While going through the error logs I encountered another error message saying "interfaceDefault.pjx: invalid library". FYI, i will also add the screenshot of that error message. I think due to some error in the libs I am able to start the ROS server in CS9.
![IMG_0311](https://user-images.githubusercontent.com/78215878/121533349-d2892e00-ca1d-11eb-9ad8-22d08c794ca9.jpg)

**Comment by JohannesFriedrich** [comment]
Indeed, the _UserInterface_ library is the problem. Did you change something in this library? I think the best way is to remove the _UserInterface_ completely from the controller and copy it again from your PC.

**Comment by AshwathamanGovind** [comment]
As expected, The issue was because of a corrupt file in UserInterface library. After i sent that via again via Transfer manager now I am able to start the ros_server application. But i am facing an issue while i try to connect to the robot from ROS. I getting this error:- 

 **Exception while loading database plugin 'warehouse_ros_mongo::MongoDatabaseConnection': According to the loaded plugin descriptions the class warehouse_ros_mongo::MongoDatabaseConnection with base class type warehouse_ros::DatabaseConnection does not exist. Declared types are** 

Any idea about this??

**Comment by AshwathamanGovind** [comment]
Thanks for the support @gavanderhoorn and @JohannesFriedrich
