### ISSUE TITLE
CS9 compatibility?

### ISSUE THREAD

**Issue by simonschmeisser** [ros-industrial/staubli_val3_driver#4]
We are currently discussing about having some initial experiments/trial with stäubli in about a week and the customer seems to have a tx2-60. So I'm wondering if you expect this driver to be compatible to cs9 as well? Is there anything special to watch out for?

I'll add a pr for the support package later on of course

**Comment by gavanderhoorn** [comment]
I've linked #15 here, as that would seem to resolve the incompatibilities with CS9 controllers in the code identified in this issue.

@simonschmeisser: you don't happen to have a CS9 near you to test #15, would you?

@gonzalocasas: would you perhaps see a chance to test #15? Just an SRS run would be fine.
