### ISSUE TITLE
Building-issue with simple_message trying to integrate IO control 

### ISSUE THREAD

**Issue by IvoD1998** [ros-industrial/staubli_val3_driver#41]
Hi

We are trying to integrate IO control for the CS9 controller in the driver using the FAU-FAPS driver as inspiration (https://github.com/FAU-FAPS/staubli_val3_driver/tree/faps-devel). When we try to build our workspace, we run into the following issue:

![Simple_message_issue](https://user-images.githubusercontent.com/86001872/128867412-65a09087-dbce-4d97-b006-35c896fc8381.png)

On its own, the simple_message package does build without any issues, so we suspect it to be a CMake issue, but are uncertain on how to fix it. Does anybody know a solution?

Thank you in advance!
Kind regards

**Comment by gavanderhoorn** [comment]
First: please do not post screenshots of terminals. It's all text, so just copy-paste the text into a [markdown code block](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

As to your problem, see https://github.com/ros-industrial/abb_driver/pull/12 for a fix in another `simple_message`/`industrial_robot_client` based driver.
