### ISSUE TITLE
Val3 Driver Version Requirements Qestion

### ISSUE THREAD

**Issue by JGittles** [ros-industrial/staubli_val3_driver#46]
Hi All,

I am trying to do realtime control with the FAU fork of ros_Industrial. while running in SRS after acquiring the motion addon from staubli I could not run the sim and noticed that the ros_industrial fork uses val3 s7.9.1 and my controller is running either 7.6 and 7.11.2. do these versions need to be an exact match for successful execution?

**Comment by JGittles** [comment]
additional note: I am unsure of the specificity of the motion addon for Val3 version compatibility but I have the one at least intended for s7.6.

**Comment by gavanderhoorn** [comment]
I can't comment on the exact version requirement. The work was done in a fork, isolated.

The original author(s) would have to provide that information.

**Comment by gavanderhoorn** [comment]
Perhaps @enginkarlidag can comment.

**Comment by JGittles** [comment]
![image](https://user-images.githubusercontent.com/58196263/136044253-2280ce9c-9bbe-4e63-aad3-08fa066c6bb7.png)

here is also a relevant image of the error

**Comment by enginkarlidag** [comment]
The VAL3 version could be anything from s7.7.2 or greater (for CS8 controllers). The minimum version is given as a requirement as described in the [README](https://github.com/ros-industrial/staubli_val3_driver/blob/master/staubli_val3_driver/README.md#requirements) of this repo.

And just to avoid misunderstandings: The following information mainly refers to our fork of the driver!

So our project seems to be saved with version s7.9.1 but it should be possible to use any version (>= s7.7.2) to run it. You just have to make sure that the required add-on is installed and the sockets are configured as described in the [README](https://github.com/FAU-FAPS/staubli_val3_driver/tree/faps-devel/staubli_val3_driver#configuration).

Afaik, you always need the corresponding add-on(s) for a specific VAL3 version. For example, if you want to use s7.11.2 then you should get and install the add-on for this version. Btw, you must also enable the add-on for your controller in SRS explicitly. You can do that directly in the "New Cell Wizard" while creating a new cell or afterwards in the controller configuration. Just right-click on the controller in the "Cell Explorer" and go to "Controller Configuration". There you should have a tab called "Add Ons" if you have installed the correct version of the add-on. I was able to reproduce your error when the add-on was disabled. So enabling the add-on should fix it. This is only required for the emulated controller in SRS. For the real controller I think you get .so files which you have to copy via an FTP connection to the controller and they should be "enabled" after a reboot automatically.

![2021-10-05_23-37-54](https://user-images.githubusercontent.com/61935486/136106835-d2920788-f690-4222-ba62-4a916b19f8b3.jpg)

**Comment by gavanderhoorn** [comment]
@JGittles: could you confirm that you've been able to resolve the problems you were having with the information @enginkarlidag has provided?

**Comment by JGittles** [comment]
@gavanderhoorn yes Engin has fixed my issue and I was successfully able to run this in srs. issue has been closed
